apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresql
  namespace: airflow
spec:
  serviceName: postgresql-service
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgresql
        image: postgres:15.1-alpine
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "airflow"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: airflow-db-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-db-secret
              key: postgres-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
        
        # Health Check 추가
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U airflow -d airflow
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
        
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U airflow -d airflow
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U airflow -d airflow
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        
  
  # volumeClaimTemplates - StatefulSet의 핵심!
  volumeClaimTemplates:
  - metadata:
      name: postgresql-storage
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 5Gi
