apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: airflow
type: Opaque
data:
  postgres-user: YWlyZmxvdw==           # airflow
  postgres-password: YWlyZmxvdzEyMw==   # airflow123
  postgres-db: YWlyZmxvdw==             # airflow