executor: KubernetesExecutor

# PostgreSQL 연결 설정
data:
  metadataConnection:
    user: airflow
    pass: airflow123
    protocol: postgresql
    host: postgresql-service.airflow.svc.cluster.local
    port: 5432
    db: airflow
    sslmode: disable

dags:
  gitSync:
    enabled: true
    repo: "https://github.com/choiyounghwan123/cryptoflow-k8s-airflow.git"
    branch: main
    subPath: "dags"

kubernetesExecutor:
  deleteWorkerPods: false
  deleteWorkerPodsOnSuccess: false
  deleteWorkerPodsOnFailure: false

serviceAccount:
  create: true
  name: airflow

rbac:
  create: true

postgresql:
  enabled: false

# 기본 설정 사용 - Secret은 자동으로 생성되도록
createUserJob:
  useHelmHooks: false

migrateDatabaseJob:
  useHelmHooks: false

# 로그 설정 - 원격 로그 비활성화하고 로컬 로그 사용
logs:
  persistence:
    enabled: true
    size: 2Gi
    storageClassName: ""  # 기본 스토리지 클래스 사용

config:
  logging:
    remote_logging: "False"
    logging_level: "INFO"
    remote_base_log_folder: ""
    remote_log_conn_id: ""
    colored_console_log: "True"
  core:
    logging_config_class: ""
    enable_xcom_pickling: "False"
  kubernetes_executor:
    delete_worker_pods: "False"
    delete_worker_pods_on_success: "False" 
    delete_worker_pods_on_failure: "False"
    worker_pods_creation_batch_size: "1"
    
# Airflow 환경 변수로 강제 설정
env:
  - name: AIRFLOW__LOGGING__REMOTE_LOGGING
    value: "False"
  - name: AIRFLOW__CORE__ENABLE_XCOM_PICKLING  
    value: "False"
  - name: AIRFLOW__KUBERNETES_EXECUTOR__DELETE_WORKER_PODS
    value: "False"