apiVersion: batch/v1
kind: Job
metadata:
  name: airflow-db-init
  namespace: airflow
spec:
  template:
    spec:
      serviceAccountName: airflow
      restartPolicy: OnFailure
      containers:
      - name: airflow-db-init
        image: apache/airflow:2.7.1-python3.11
        command:
        - bash
        - -c
        - |
          # PostgreSQL 연결 대기 (환경변수 사용)
          until pg_isready -h postgresql-service -p 5432 -U $POSTGRES_USER; do
            echo "PostgreSQL 대기 중..."
            sleep 5
          done
          
          # 데이터베이스 초기화
          airflow db init
          
          # 관리자 계정 생성 (환경변수 사용)
          airflow users create \
            --username $ADMIN_USERNAME \
            --password $ADMIN_PASSWORD \
            --firstname Admin \
            --lastname User \
            --role Admin \
            --email $ADMIN_EMAIL || echo "User already exists"
        envFrom:
        - configMapRef:
            name: airflow-config
        env:
        # Fernet Key
        - name: AIRFLOW__CORE__FERNET_KEY
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: fernet-key
        
        # PostgreSQL 연결 정보
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: postgres-password
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: postgres-db
        - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          value: "postgresql://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgresql-service:5432/$(POSTGRES_DB)"
        
        # Airflow 관리자 계정 정보
        - name: ADMIN_USERNAME
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: admin-username
        - name: ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: admin-password
        - name: ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: airflow-secret
              key: admin-email
