apiVersion: v1
kind: Secret
metadata:
  name: airflow-secret
  namespace: airflow
type: Opaque
stringData:
  fernet-key: UEJiQ2M2dlVJOVNNdHRvTnVMTEV5TzFjWnN3WkNCMzQ=
  sql_alchemy_conn: postgresql://airflow:airflow123@airflow-postgresql.airflow.svc.cluster.local:5432/airflow
  web_server_secret_key: d2ee0b244ab182fb5df43be595b97716